# Generated by Django 3.0.6 on 2020-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='receive_news',
            field=models.BooleanField(blank=True, default=True, verbose_name='Receive news and etc.'),
        ),
    ]
